### ISSUE TITLE
Application run failed

### ISSUE THREAD

**Issue by ManuISEN** [Jolt151/spotify2m3u#2]
Hi @Jolt151,

I've tested your application but it throws an exception.
I use OpenJDK13 on a Mac mini, application.properties is set as follow:

>manu@Mac-mini-de-Emmanuel ~ % cat /Volumes/Untitled/application.properties
library_folder = /Volumes/Untitled/Extracted_from_spotify

Logs and exception thrown:

> manu@Mac-mini-de-Emmanuel ~ % /Users/manu/Downloads/jdk-13.0.2.jdk/Contents/Home/bin/java -jar /Volumes/Untitled/spotify2m3u.jar

>  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.2.RELEASE)

>2021-08-08 11:05:35.041  INFO 1156 --- [           main] com.test.ApplicationKt                   : Starting ApplicationKt v1.0-SNAPSHOT on Mac-mini-de-Emmanuel.local with PID 1156 (/Volumes/Untitled/spotify2m3u.jar started by manu in /Users/manu)
2021-08-08 11:05:35.043  INFO 1156 --- [           main] com.test.ApplicationKt                   : No active profile set, falling back to default profiles: default
2021-08-08 11:05:35.295  WARN 1156 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.test.Application]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'restController' for bean class [com.test.controller.RestController] conflicts with existing, non-compatible bean definition of same name and class [com.test.RestController]
2021-08-08 11:05:35.316 ERROR 1156 --- [           main] o.s.boot.SpringApplication               : Application run failed

>org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.test.Application]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'restController' for bean class [com.test.controller.RestController] conflicts with existing, non-compatible bean definition of same name and class [com.test.RestController]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:184) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:325) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:242) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
	at com.test.ApplicationKt.main(Application.kt:11) ~[classes!/:1.0-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[spotify2m3u.jar:1.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[spotify2m3u.jar:1.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[spotify2m3u.jar:1.0-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[spotify2m3u.jar:1.0-SNAPSHOT]
Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'restController' for bean class [com.test.controller.RestController] conflicts with existing, non-compatible bean definition of same name and class [com.test.RestController]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.checkCandidate(ClassPathBeanDefinitionScanner.java:349) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:287) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:132) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:290) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:245) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:202) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:170) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	... 21 common frames omitted`

It seems to be linked with the class com.test.controller.RestController

I also tested on Windows with latest JDK, the exception is the same.
Which version of Java do you use ?

Best regards,

Emmanuel

**Comment by Geri-Borbas** [comment]
I have the very same issue. @Jolt151 Is there anything we can do?

**Comment by Jolt151** [comment]
I haven't run this in a long time, and I may not get a chance to test this out. I'm not sure why this used to work but doesn't anymore, but peeking at the code, I spot this:

https://github.com/Jolt151/spotify2m3u/blob/master/src/main/kotlin/com/test/RestController.kt#L11-L17

Probably the application class name is conflicting with the spring class and annotation name. You can try to refactor that name and see if that makes it work, and feel free to submit a pr if so. The code is pretty simple 🙂

**Comment by Geri-Borbas** [comment]
Thanks for getting back! I can't compile, I have no Kotlin environment setup. I'll just wait until you/someone perhaps find some time to look at it. :D

**Comment by invertedEcho** [comment]
Hmm, currently trying to fix those errors up. Sadly not a matter of simple refactoring. Problem is that I don't have experience with Kotlin. Also, what is really confusing me, that intellij is telling me that pretty much all classes are unused... Probably a false positive? Something is wrong though. I will look if I can fix the errors.

also, there are two RestController and two SiteController, which is confusing

**Comment by invertedEcho** [comment]
Well, I did make some progress.
I got so far that localhost:8080 shows this:

![2022-04-13-201841_676x235_scrot](https://user-images.githubusercontent.com/80119822/163244803-db89cadd-7dc4-4c4d-8d0e-0fdd256ac792.png)

Console doesn't really show anything. I can open the index.html but that doesn't really help anything (ofc?)
@Jolt151

**Comment by Luke-Mason** [comment]
:( This project looked so promising :( :(
